//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binary_Digit_Blog {
    
    
    public partial class _Default {
        
        /// <summary>
        /// BlogPostPreviews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Binary_Digit_Blog.Controls.BlogPostPreviews BlogPostPreviews;
        
        /// <summary>
        /// DefaultAsideContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Binary_Digit_Blog.Controls.DefaultAsideContent DefaultAsideContent;
    }
}
