//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binary_Digit_Blog.Controls {
    
    
    public partial class DefaultAsideContent {
        
        /// <summary>
        /// SearchBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Binary_Digit_Blog.Controls.SearchBox SearchBox;
        
        /// <summary>
        /// TagCloud control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Binary_Digit_Blog.Controls.TagCloud TagCloud;
        
        /// <summary>
        /// ArticleArchiveTree control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Binary_Digit_Blog.Controls.ArticleArchiveTree ArticleArchiveTree;
    }
}
